name: tac-edit

services:
  tac-edit:
    container_name: TAC-Edit
    restart: unless-stopped
    image: ghcr.io/solo-web-works/tac-edit:main
    user: 33:33 # Runs the container as the www-data user and group

    environment:
      # Sets the user and group for Apache inside the container
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

    ports:
      - "4040:80" # Maps port 80 in the container to port 4040 on the host.  Change as needed.

    volumes:
      - /opt/t-a-c-proxy/traefik/config:/data # Required, mounts the Traefik config folder on the host to /data in the container
      - /opt/tac-edit/logs:/logs            # Optional, mounts the logs folder in the container on the host
      - /opt/tac-edit/versions:/versions    # Optional, mounts the versions folder in the container on the host

    labels:
      - com.centurylinklabs.watchtower.enable=false # Optional, disables Watchtower if it's running on the host
