name: tac-edit

services:
  tac-edit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TAC-Edit
    restart: unless-stopped

    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

    ports:
      - "4040:80"  # Maps port 80 in the container to port 8080 on the host

    volumes:
      - /opt/tac-edit/config-test:/data  # Mounts the data folder on the host to /data in the container
      - /opt/tac-edit/config/php.ini:/usr/local/etc/php/php.ini  # Custom PHP configuration
