name: tac-edit

services:
  tac-edit:
    container_name: TAC-Edit
    restart: unless-stopped
    image: ghcr.io/solo-web-works/tac-edit:main
    user: 33:33  # Runs the container as the www-data user and group

    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

    ports:
      - "4040:80"  # Maps port 80 in the container to port 8080 on the host

    volumes:
      - /opt/t-a-c-proxy/traefik/config:/data  # Mounts the data folder on the host to /data in the container
      - /opt/tac-edit/logs:/logs  # Mounts the logs folder on the host to /logs in the container
      - /opt/tac-edit/versions:/versions  # Mounts the versions folder on the host to /versions in the container
      - /opt/tac-edit/config/php.ini:/usr/local/etc/php/php.ini  # Custom PHP configuration

    labels:
      - "com.centurylinklabs.watchtower.enable=false" # Disables Watchtower
